// Code generated by goctl. DO NOT EDIT.
package model

import (
	"context"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

type ApprovalModel interface {
	Insert(ctx context.Context, data *Approval) error
	FindOne(ctx context.Context, id string) (*Approval, error)
	Update(ctx context.Context, data *Approval) error
	Delete(ctx context.Context, id string) error
	List(ctx context.Context, userId string, approvalType int, page, count int) ([]*Approval, int64, error)
}

type defaultApprovalModel struct {
	col *mongo.Collection
}

func NewApprovalModel(db *mongo.Database) ApprovalModel {
	col := db.Collection("approval")
	return &defaultApprovalModel{
		col: col,
	}
}

func (m *defaultApprovalModel) Insert(ctx context.Context, data *Approval) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now().Unix()
		data.UpdateAt = time.Now().Unix()
	}

	_, err := m.col.InsertOne(ctx, data)
	return err
}

func (m *defaultApprovalModel) FindOne(ctx context.Context, id string) (*Approval, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Approval
	err = m.col.FindOne(ctx, bson.M{"_id": oid}).Decode(&data)
	switch err {
	case nil:
		return &data, nil
	case mongo.ErrNoDocuments:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultApprovalModel) Update(ctx context.Context, data *Approval) error {
	data.UpdateAt = time.Now().Unix()
	_, err := m.col.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return err
}

func (m *defaultApprovalModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}
	_, err = m.col.DeleteOne(ctx, bson.M{"_id": oid})
	return err
}

func (m *defaultApprovalModel) List(ctx context.Context, userId string, approvalType int, page, count int) ([]*Approval, int64, error) {
	var conditions []bson.M

	if userId != "" {
		// 查询用户参与的审批（包括创建者和审批人）
		conditions = append(conditions, bson.M{
			"$or": []bson.M{
				{"userId": userId},
				{"participation": userId},
			},
		})
	}

	if approvalType > 0 {
		conditions = append(conditions, bson.M{"type": ApprovalType(approvalType)})
	}

	filter := bson.M{}
	if len(conditions) > 0 {
		filter["$and"] = conditions
	}

	total, err := m.col.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	if page < 1 {
		page = 1
	}
	if count < 1 {
		count = 10
	}
	skip := int64((page - 1) * count)

	opts := options.Find().SetSkip(skip).SetLimit(int64(count)).SetSort(bson.M{"createAt": -1})
	cursor, err := m.col.Find(ctx, filter, opts)
	if err != nil {
		return nil, 0, err
	}
	defer cursor.Close(ctx)

	var approvals []*Approval
	if err = cursor.All(ctx, &approvals); err != nil {
		return nil, 0, err
	}

	return approvals, total, nil
}
