// Code generated by goctl. DO NOT EDIT.
package model

import (
	"context"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

type DepartmentuserModel interface {
	Insert(ctx context.Context, data *Departmentuser) error
	FindOne(ctx context.Context, id string) (*Departmentuser, error)
	Update(ctx context.Context, data *Departmentuser) error
	Delete(ctx context.Context, id string) error
	FindByDepId(ctx context.Context, depId string) ([]*Departmentuser, error)
	FindByUserId(ctx context.Context, userId string) ([]*Departmentuser, error)
	DeleteByDepIdAndUserId(ctx context.Context, depId, userId string) error
	DeleteByDepId(ctx context.Context, depId string) error
	FindByDepIds(ctx context.Context, depIds []string) ([]*Departmentuser, error)
}

type defaultDepartmentuserModel struct {
	col *mongo.Collection
}

func NewDepartmentuserModel(db *mongo.Database) DepartmentuserModel {
	col := db.Collection("departmentuser")
	return &defaultDepartmentuserModel{
		col: col,
	}
}

func (m *defaultDepartmentuserModel) Insert(ctx context.Context, data *Departmentuser) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now().Unix()
		data.UpdateAt = time.Now().Unix()
	}

	_, err := m.col.InsertOne(ctx, data)
	return err
}

func (m *defaultDepartmentuserModel) FindOne(ctx context.Context, id string) (*Departmentuser, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Departmentuser
	err = m.col.FindOne(ctx, bson.M{"_id": oid}).Decode(&data)
	switch err {
	case nil:
		return &data, nil
	case mongo.ErrNoDocuments:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDepartmentuserModel) Update(ctx context.Context, data *Departmentuser) error {
	data.UpdateAt = time.Now().Unix()
	_, err := m.col.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return err
}

func (m *defaultDepartmentuserModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}
	_, err = m.col.DeleteOne(ctx, bson.M{"_id": oid})
	return err
}

func (m *defaultDepartmentuserModel) FindByDepId(ctx context.Context, depId string) ([]*Departmentuser, error) {
	cursor, err := m.col.Find(ctx, bson.M{"depId": depId})
	if err != nil {
		return nil, err
	}
	defer cursor.Close(ctx)

	var users []*Departmentuser
	if err = cursor.All(ctx, &users); err != nil {
		return nil, err
	}
	return users, nil
}

func (m *defaultDepartmentuserModel) FindByUserId(ctx context.Context, userId string) ([]*Departmentuser, error) {
	cursor, err := m.col.Find(ctx, bson.M{"userId": userId})
	if err != nil {
		return nil, err
	}
	defer cursor.Close(ctx)

	var users []*Departmentuser
	if err = cursor.All(ctx, &users); err != nil {
		return nil, err
	}
	return users, nil
}

func (m *defaultDepartmentuserModel) DeleteByDepIdAndUserId(ctx context.Context, depId, userId string) error {
	_, err := m.col.DeleteOne(ctx, bson.M{"depId": depId, "userId": userId})
	return err
}

func (m *defaultDepartmentuserModel) DeleteByDepId(ctx context.Context, depId string) error {
	_, err := m.col.DeleteMany(ctx, bson.M{"depId": depId})
	return err
}

func (m *defaultDepartmentuserModel) FindByDepIds(ctx context.Context, depIds []string) ([]*Departmentuser, error) {
	cursor, err := m.col.Find(ctx, bson.M{"depId": bson.M{"$in": depIds}})
	if err != nil {
		return nil, err
	}
	defer cursor.Close(ctx)

	var users []*Departmentuser
	if err = cursor.All(ctx, &users); err != nil {
		return nil, err
	}
	return users, nil
}
