// Code generated by goctl. DO NOT EDIT.
package model

import (
	"context"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

type DepartmentModel interface {
	Insert(ctx context.Context, data *Department) error
	FindOne(ctx context.Context, id string) (*Department, error)
	Update(ctx context.Context, data *Department) error
	Delete(ctx context.Context, id string) error
	FindAll(ctx context.Context) ([]*Department, error)
	FindByParentId(ctx context.Context, parentId string) ([]*Department, error)
	FindByIds(ctx context.Context, ids []string) ([]*Department, error)
}

type defaultDepartmentModel struct {
	col *mongo.Collection
}

func NewDepartmentModel(db *mongo.Database) DepartmentModel {
	col := db.Collection("department")
	return &defaultDepartmentModel{
		col: col,
	}
}

func (m *defaultDepartmentModel) Insert(ctx context.Context, data *Department) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now().Unix()
		data.UpdateAt = time.Now().Unix()
	}

	_, err := m.col.InsertOne(ctx, data)
	return err
}

func (m *defaultDepartmentModel) FindOne(ctx context.Context, id string) (*Department, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Department
	err = m.col.FindOne(ctx, bson.M{"_id": oid}).Decode(&data)
	switch err {
	case nil:
		return &data, nil
	case mongo.ErrNoDocuments:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDepartmentModel) Update(ctx context.Context, data *Department) error {
	data.UpdateAt = time.Now().Unix()
	_, err := m.col.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return err
}

func (m *defaultDepartmentModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}
	_, err = m.col.DeleteOne(ctx, bson.M{"_id": oid})
	return err
}

func (m *defaultDepartmentModel) FindAll(ctx context.Context) ([]*Department, error) {
	cursor, err := m.col.Find(ctx, bson.M{})
	if err != nil {
		return nil, err
	}
	defer cursor.Close(ctx)

	var departments []*Department
	if err = cursor.All(ctx, &departments); err != nil {
		return nil, err
	}
	return departments, nil
}

func (m *defaultDepartmentModel) FindByParentId(ctx context.Context, parentId string) ([]*Department, error) {
	cursor, err := m.col.Find(ctx, bson.M{"parentId": parentId})
	if err != nil {
		return nil, err
	}
	defer cursor.Close(ctx)

	var departments []*Department
	if err = cursor.All(ctx, &departments); err != nil {
		return nil, err
	}
	return departments, nil
}

func (m *defaultDepartmentModel) FindByIds(ctx context.Context, ids []string) ([]*Department, error) {
	oids := make([]primitive.ObjectID, 0, len(ids))
	for _, id := range ids {
		oid, err := primitive.ObjectIDFromHex(id)
		if err != nil {
			continue
		}
		oids = append(oids, oid)
	}

	cursor, err := m.col.Find(ctx, bson.M{"_id": bson.M{"$in": oids}})
	if err != nil {
		return nil, err
	}
	defer cursor.Close(ctx)

	var departments []*Department
	if err = cursor.All(ctx, &departments); err != nil {
		return nil, err
	}
	return departments, nil
}
