// Code generated by goctl. DO NOT EDIT.
package model

import (
	"context"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

type DepartmentModel interface {
	Insert(ctx context.Context, data *Department) error
	FindOne(ctx context.Context, id string) (*Department, error)
	Update(ctx context.Context, data *Department) error
	Delete(ctx context.Context, id string) error
}

type defaultDepartmentModel struct {
	col *mongo.Collection
}

func NewDepartmentModel(db *mongo.Database) DepartmentModel {
	col := db.Collection("department")
	return &defaultDepartmentModel{
		col: col,
	}
}

func (m *defaultDepartmentModel) Insert(ctx context.Context, data *Department) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now().Unix()
		data.UpdateAt = time.Now().Unix()
	}

	_, err := m.col.InsertOne(ctx, data)
	return err
}

func (m *defaultDepartmentModel) FindOne(ctx context.Context, id string) (*Department, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Department
	err = m.col.FindOne(ctx, bson.M{"_id": oid}).Decode(&data)
	switch err {
	case nil:
		return &data, nil
	case mongo.ErrNoDocuments:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDepartmentModel) Update(ctx context.Context, data *Department) error {
	data.UpdateAt = time.Now().Unix()
	_, err := m.col.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return err
}

func (m *defaultDepartmentModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}
	_, err = m.col.DeleteOne(ctx, bson.M{"_id": oid})
	return err
}
