// Code generated by goctl. DO NOT EDIT.
package model

import (
	"context"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

type TodoRecordModel interface {
	Insert(ctx context.Context, data *TodoRecord) error
	FindOne(ctx context.Context, id string) (*TodoRecord, error)
	Update(ctx context.Context, data *TodoRecord) error
	Delete(ctx context.Context, id string) error
	FindByTodoId(ctx context.Context, todoId string) ([]*TodoRecord, error)
	DeleteByTodoId(ctx context.Context, todoId string) error
}

type defaultTodoRecordModel struct {
	col *mongo.Collection
}

func NewTodoRecordModel(db *mongo.Database) TodoRecordModel {
	col := db.Collection("todo_record")
	return &defaultTodoRecordModel{
		col: col,
	}
}

func (m *defaultTodoRecordModel) Insert(ctx context.Context, data *TodoRecord) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now().Unix()
		data.UpdateAt = time.Now().Unix()
	}

	_, err := m.col.InsertOne(ctx, data)
	return err
}

func (m *defaultTodoRecordModel) FindOne(ctx context.Context, id string) (*TodoRecord, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data TodoRecord
	err = m.col.FindOne(ctx, bson.M{"_id": oid}).Decode(&data)
	switch err {
	case nil:
		return &data, nil
	case mongo.ErrNoDocuments:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTodoRecordModel) Update(ctx context.Context, data *TodoRecord) error {
	data.UpdateAt = time.Now().Unix()
	_, err := m.col.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return err
}

func (m *defaultTodoRecordModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}
	_, err = m.col.DeleteOne(ctx, bson.M{"_id": oid})
	return err
}

func (m *defaultTodoRecordModel) FindByTodoId(ctx context.Context, todoId string) ([]*TodoRecord, error) {
	cursor, err := m.col.Find(ctx, bson.M{"todoId": todoId})
	if err != nil {
		return nil, err
	}
	defer cursor.Close(ctx)

	var records []*TodoRecord
	if err = cursor.All(ctx, &records); err != nil {
		return nil, err
	}
	return records, nil
}

func (m *defaultTodoRecordModel) DeleteByTodoId(ctx context.Context, todoId string) error {
	_, err := m.col.DeleteMany(ctx, bson.M{"todoId": todoId})
	return err
}
