// Code generated by goctl. DO NOT EDIT.
package model

import (
	"context"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

type UserModel interface {
	Insert(ctx context.Context, data *User) error
	FindOne(ctx context.Context, id string) (*User, error)
	FindByName(ctx context.Context, name string) (*User, error)
	FindAdminUser(ctx context.Context) (*User, error)
	Update(ctx context.Context, data *User) error
	Delete(ctx context.Context, id string) error
	List(ctx context.Context, ids []string, name string, page, count int) ([]*User, int64, error)
}

type defaultUserModel struct {
	col *mongo.Collection
}

func NewUserModel(db *mongo.Database) UserModel {
	col := db.Collection("user")
	return &defaultUserModel{
		col: col,
	}
}

func (m *defaultUserModel) Insert(ctx context.Context, data *User) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now().Unix()
		data.UpdateAt = time.Now().Unix()
	}

	_, err := m.col.InsertOne(ctx, data)
	return err
}

func (m *defaultUserModel) FindOne(ctx context.Context, id string) (*User, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data User
	err = m.col.FindOne(ctx, bson.M{"_id": oid}).Decode(&data)
	switch err {
	case nil:
		return &data, nil
	case mongo.ErrNoDocuments:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) Update(ctx context.Context, data *User) error {
	data.UpdateAt = time.Now().Unix()
	_, err := m.col.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return err
}

func (m *defaultUserModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}
	_, err = m.col.DeleteOne(ctx, bson.M{"_id": oid})
	return err
}

func (m *defaultUserModel) FindByName(ctx context.Context, name string) (*User, error) {
	var user User
	err := m.col.FindOne(ctx, bson.M{"name": name}).Decode(&user)
	switch err {
	case nil:
		return &user, nil
	case mongo.ErrNoDocuments:
		return nil, ErrNotFindUser
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindAdminUser(ctx context.Context) (*User, error) {
	var user User
	err := m.col.FindOne(ctx, bson.M{"isAdmin": true}).Decode(&user)
	switch err {
	case nil:
		return &user, nil
	case mongo.ErrNoDocuments:
		return nil, ErrNotFindUser
	default:
		return nil, err
	}
}

func (m *defaultUserModel) List(ctx context.Context, ids []string, name string, page, count int) ([]*User, int64, error) {
	filter := bson.M{}

	// 按ID列表查询
	if len(ids) > 0 {
		oids := make([]primitive.ObjectID, 0, len(ids))
		for _, id := range ids {
			oid, err := primitive.ObjectIDFromHex(id)
			if err != nil {
				continue
			}
			oids = append(oids, oid)
		}
		if len(oids) > 0 {
			filter["_id"] = bson.M{"$in": oids}
		}
	}

	// 按用户名模糊查询
	if name != "" {
		filter["name"] = bson.M{"$regex": name, "$options": "i"}
	}

	// 获取总数
	total, err := m.col.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	// 分页查询
	if page < 1 {
		page = 1
	}
	if count < 1 {
		count = 10
	}
	skip := int64((page - 1) * count)

	findOptions := options.Find()
	findOptions.SetSkip(skip)
	findOptions.SetLimit(int64(count))

	cursor, err := m.col.Find(ctx, filter, findOptions)
	if err != nil {
		return nil, 0, err
	}
	defer cursor.Close(ctx)

	var users []*User
	if err = cursor.All(ctx, &users); err != nil {
		return nil, 0, err
	}

	return users, total, nil
}

func int64Ptr(i int64) *int64 {
	return &i
}
