// Code generated by goctl. DO NOT EDIT.
package domain

type User struct {
	Id       string `json:"id,omitempty"`       // 用户ID
	Password string `json:"password,omitempty"` // 密码
	Name     string `json:"name,omitempty"`     // 用户名
	Status   int    `json:"status,omitempty"`   // 状态：0=禁用 1=启用
}

type UserListReq struct {
	Ids   []string `json:"ids,omitempty"`   // 用户ID列表
	Name  string   `json:"name,omitempty"`  // 用户名模糊搜索
	Page  int      `json:"page,omitempty"`  // 页码
	Count int      `json:"count,omitempty"` // 每页数量
}

type UserListResp struct {
	Count int64   `json:"count"` // 总记录数
	List  []*User `json:"data"`  // 用户列表
}

type LoginReq struct {
	Name     string `json:"name,omitempty"`     // 用户名
	Password string `json:"password,omitempty"` // 密码
}

type LoginResp struct {
	Status       int    `json:"status,omitempty"`       // 状态：0=失败 1=成功
	Id           string `json:"id,omitempty"`           // 用户ID
	Name         string `json:"name,omitempty"`         // 用户名
	AccessToken  string `json:"token,omitempty"`        // JWT令牌
	AccessExpire int64  `json:"accessExpire,omitempty"` // 过期时间
	RefreshAfter int64  `json:"refreshAfter,omitempty"` // 刷新时间
}

type UpdatePasswordReq struct {
	Id     string `json:"id"`     // 用户ID
	OldPwd string `json:"oldPwd"` // 原密码
	NewPwd string `json:"newPwd"` // 新密码
}

type IdPathReq struct {
	Id string `uri:"id,omitempty"` // uri 标签表示从 URL 路径获取参数
}

type IdResp struct {
	Id string `json:"id,omitempty"` // json 标签表示 JSON 序列化字段名
}

type IdRespInfo struct {
	Code int     `json:"code"`
	Data *IdResp `json:"data"`
}

type Department struct {
	Id         string        `json:"id, omitempty"`         // 部门ID
	Name       string        `json:"name, omitempty"`       // 部门名称
	ParentId   string        `json:"parentId, omitempty"`   // 父部门ID
	ParentPath string        `json:"parentPath, omitempty"` // 父部门路径
	Level      int           `json:"level, omitempty"`      // 部门层级
	LeaderId   string        `json:"leaderId, omitempty"`   // 部门负责人ID
	Leader     string        `json:"leader, omitempty"`     // 部门负责人姓名
	Count      int64         `json:"count, omitempty"`      // 部门人数
	Child      []*Department `json:"child, omitempty"`      // 子部门列表
}

type DepartmentUser struct {
	Id       string `json:"id,omitempty"`       // 关联ID
	UserId   string `json:"user,omitempty"`     // 用户ID
	DepId    string `json:"dep,omitempty"`      // 部门ID
	UserName string `json:"userName,omitempty"` // 用户姓名
}

type DepartmentListReq struct {
	DepId  string   `json:"depId,omitempty"`  // 单个部门ID
	DepIds []string `json:"depIds,omitempty"` // 多个部门ID列表
}

type DepartmentPathReq struct {
	DepId  string `path:"depId,omitempty"`  // 部门ID路径参数
	UserId string `path:"userId,omitempty"` // 用户ID路径参数
}

type SetDepartmentUser struct {
	DepId   string   `json:"depId"`   // 部门ID
	UserIds []string `json:"userIds"` // 用户ID列表
}

type AddDepartmentUser struct {
	DepId  string `json:"depId"`  // 部门ID
	UserId string `json:"userId"` // 要添加的用户ID
}

type RemoveDepartmentUser struct {
	DepId  string `json:"depId"`  // 部门ID
	UserId string `json:"userId"` // 要删除的用户ID
}

type DepartmentSoaResp struct {
	Id       string            `json:"id, omitempty"`       // 部门ID
	Name     string            `json:"name, omitempty"`     // 部门名称
	ParentId string            `json:"parentId, omitempty"` // 父部门ID
	Level    int               `json:"level, omitempty"`    // 部门层级
	LeaderId string            `json:"leaderId, omitempty"` // 负责人ID
	Leader   string            `json:"leader, omitempty"`   // 负责人姓名
	Count    int64             `json:"count, omitempty"`    // 部门人数
	Users    []*DepartmentUser `json:"users, omitempty"`    // 部门用户列表
	Child    []*Department     `json:"child, omitempty"`    // 子部门列表
}
