// Code generated by goctl. DO NOT EDIT.
package domain

type User struct {
	Id       string `json:"id,omitempty"`       // 用户ID
	Password string `json:"password,omitempty"` // 密码
	Name     string `json:"name,omitempty"`     // 用户名
	Status   int    `json:"status,omitempty"`   // 状态：0=禁用 1=启用
}

type UserListReq struct {
	Ids   []string `json:"ids,omitempty"`   // 用户ID列表
	Name  string   `json:"name,omitempty"`  // 用户名模糊搜索
	Page  int      `json:"page,omitempty"`  // 页码
	Count int      `json:"count,omitempty"` // 每页数量
}

type UserListResp struct {
	Count int64   `json:"count"` // 总记录数
	List  []*User `json:"data"`  // 用户列表
}

type LoginReq struct {
	Name     string `json:"name,omitempty"`     // 用户名
	Password string `json:"password,omitempty"` // 密码
}

type LoginResp struct {
	Status       int    `json:"status,omitempty"`       // 状态：0=失败 1=成功
	Id           string `json:"id,omitempty"`           // 用户ID
	Name         string `json:"name,omitempty"`         // 用户名
	AccessToken  string `json:"token,omitempty"`        // JWT令牌
	AccessExpire int64  `json:"accessExpire,omitempty"` // 过期时间
	RefreshAfter int64  `json:"refreshAfter,omitempty"` // 刷新时间
}

type UpdatePasswordReq struct {
	Id     string `json:"id"`     // 用户ID
	OldPwd string `json:"oldPwd"` // 原密码
	NewPwd string `json:"newPwd"` // 新密码
}

type IdPathReq struct {
	Id string `uri:"id,omitempty"` // uri 标签表示从 URL 路径获取参数
}

type IdResp struct {
	Id string `json:"id,omitempty"` // json 标签表示 JSON 序列化字段名
}

type IdRespInfo struct {
	Code int     `json:"code"`
	Data *IdResp `json:"data"`
}
